/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
)

// checks if the DirectPeeringIpv4RequestConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectPeeringIpv4RequestConnection{}

// DirectPeeringIpv4RequestConnection struct for DirectPeeringIpv4RequestConnection
type DirectPeeringIpv4RequestConnection struct {
	Uuid                 *string `json:"uuid,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DirectPeeringIpv4RequestConnection DirectPeeringIpv4RequestConnection

// NewDirectPeeringIpv4RequestConnection instantiates a new DirectPeeringIpv4RequestConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectPeeringIpv4RequestConnection() *DirectPeeringIpv4RequestConnection {
	this := DirectPeeringIpv4RequestConnection{}
	return &this
}

// NewDirectPeeringIpv4RequestConnectionWithDefaults instantiates a new DirectPeeringIpv4RequestConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectPeeringIpv4RequestConnectionWithDefaults() *DirectPeeringIpv4RequestConnection {
	this := DirectPeeringIpv4RequestConnection{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *DirectPeeringIpv4RequestConnection) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectPeeringIpv4RequestConnection) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *DirectPeeringIpv4RequestConnection) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *DirectPeeringIpv4RequestConnection) SetUuid(v string) {
	o.Uuid = &v
}

func (o DirectPeeringIpv4RequestConnection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectPeeringIpv4RequestConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DirectPeeringIpv4RequestConnection) UnmarshalJSON(data []byte) (err error) {
	varDirectPeeringIpv4RequestConnection := _DirectPeeringIpv4RequestConnection{}

	err = json.Unmarshal(data, &varDirectPeeringIpv4RequestConnection)

	if err != nil {
		return err
	}

	*o = DirectPeeringIpv4RequestConnection(varDirectPeeringIpv4RequestConnection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDirectPeeringIpv4RequestConnection struct {
	value *DirectPeeringIpv4RequestConnection
	isSet bool
}

func (v NullableDirectPeeringIpv4RequestConnection) Get() *DirectPeeringIpv4RequestConnection {
	return v.value
}

func (v *NullableDirectPeeringIpv4RequestConnection) Set(val *DirectPeeringIpv4RequestConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectPeeringIpv4RequestConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectPeeringIpv4RequestConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectPeeringIpv4RequestConnection(val *DirectPeeringIpv4RequestConnection) *NullableDirectPeeringIpv4RequestConnection {
	return &NullableDirectPeeringIpv4RequestConnection{value: val, isSet: true}
}

func (v NullableDirectPeeringIpv4RequestConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectPeeringIpv4RequestConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
