/*
Equinix Internet Access API

Equinix Internet Access provides direct access to the Internet with scalable bandwidth options in IBX data centers.

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eiav2

import (
	"encoding/json"
	"fmt"
)

// checks if the RoutingProtocolIpv6Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingProtocolIpv6Request{}

// RoutingProtocolIpv6Request struct for RoutingProtocolIpv6Request
type RoutingProtocolIpv6Request struct {
	// Collection of customer routes of IP Version 6 (IPv6)
	CustomerRoutes       []CustomerRouteIpv6Request `json:"customerRoutes"`
	AdditionalProperties map[string]interface{}
}

type _RoutingProtocolIpv6Request RoutingProtocolIpv6Request

// NewRoutingProtocolIpv6Request instantiates a new RoutingProtocolIpv6Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingProtocolIpv6Request(customerRoutes []CustomerRouteIpv6Request) *RoutingProtocolIpv6Request {
	this := RoutingProtocolIpv6Request{}
	this.CustomerRoutes = customerRoutes
	return &this
}

// NewRoutingProtocolIpv6RequestWithDefaults instantiates a new RoutingProtocolIpv6Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingProtocolIpv6RequestWithDefaults() *RoutingProtocolIpv6Request {
	this := RoutingProtocolIpv6Request{}
	return &this
}

// GetCustomerRoutes returns the CustomerRoutes field value
func (o *RoutingProtocolIpv6Request) GetCustomerRoutes() []CustomerRouteIpv6Request {
	if o == nil {
		var ret []CustomerRouteIpv6Request
		return ret
	}

	return o.CustomerRoutes
}

// GetCustomerRoutesOk returns a tuple with the CustomerRoutes field value
// and a boolean to check if the value has been set.
func (o *RoutingProtocolIpv6Request) GetCustomerRoutesOk() ([]CustomerRouteIpv6Request, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerRoutes, true
}

// SetCustomerRoutes sets field value
func (o *RoutingProtocolIpv6Request) SetCustomerRoutes(v []CustomerRouteIpv6Request) {
	o.CustomerRoutes = v
}

func (o RoutingProtocolIpv6Request) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingProtocolIpv6Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customerRoutes"] = o.CustomerRoutes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoutingProtocolIpv6Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerRoutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingProtocolIpv6Request := _RoutingProtocolIpv6Request{}

	err = json.Unmarshal(data, &varRoutingProtocolIpv6Request)

	if err != nil {
		return err
	}

	*o = RoutingProtocolIpv6Request(varRoutingProtocolIpv6Request)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customerRoutes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoutingProtocolIpv6Request struct {
	value *RoutingProtocolIpv6Request
	isSet bool
}

func (v NullableRoutingProtocolIpv6Request) Get() *RoutingProtocolIpv6Request {
	return v.value
}

func (v *NullableRoutingProtocolIpv6Request) Set(val *RoutingProtocolIpv6Request) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingProtocolIpv6Request) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingProtocolIpv6Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingProtocolIpv6Request(val *RoutingProtocolIpv6Request) *NullableRoutingProtocolIpv6Request {
	return &NullableRoutingProtocolIpv6Request{value: val, isSet: true}
}

func (v NullableRoutingProtocolIpv6Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingProtocolIpv6Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
