/*
Smart Hands

Request cage assistance, custom installation and equipment troubleshooting.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smarthandsv1

import (
	"encoding/json"
	"fmt"
)

// checks if the LocatePackageRequestServiceDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocatePackageRequestServiceDetails{}

// LocatePackageRequestServiceDetails Shipment Unpacking
type LocatePackageRequestServiceDetails struct {
	// Inbound Shipment Order Number
	ShipmentOrderNumber string "json:\"shipmentOrderNumber\" validate:\"regexp=^[ A-Za-z0-9~!|\\\\[\\\\]@#$%^&*()_+:\\\"<>?\\/.,;'=\\\\-\\\\{\\\\}`]{1,50}$\""
	// Tracking Number
	TrackingNumber string "json:\"trackingNumber\" validate:\"regexp=^[ A-Za-z0-9~!|\\\\[\\\\]@#$%^&*()_+:\\\"<>?\\/.,;'=\\\\-\\\\{\\\\}`]{1,200}$\""
	// Possible Location
	PossibleLocation string "json:\"possibleLocation\" validate:\"regexp=^[ A-Za-z0-9~!|\\\\[\\\\]@#$%^&*()_+:\\\"<>?\\/.,;'=\\\\-\\\\{\\\\}`]{1,200}$\""
	// Package Description
	PackageDescription string "json:\"packageDescription\" validate:\"regexp=^[ A-Za-z0-9~!|\\\\[\\\\]@#$%^&*()_+:\\\"<>?\\/.,;'=\\\\-\\\\{\\\\}`]{1,200}$\""
	// Enter any additional details that will help our technicians execute your request. You may also attach your scope of work as a document if you exceed the character limit in this field.
	ScopeOfWork          string `json:"scopeOfWork"`
	AdditionalProperties map[string]interface{}
}

type _LocatePackageRequestServiceDetails LocatePackageRequestServiceDetails

// NewLocatePackageRequestServiceDetails instantiates a new LocatePackageRequestServiceDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocatePackageRequestServiceDetails(shipmentOrderNumber string, trackingNumber string, possibleLocation string, packageDescription string, scopeOfWork string) *LocatePackageRequestServiceDetails {
	this := LocatePackageRequestServiceDetails{}
	this.ShipmentOrderNumber = shipmentOrderNumber
	this.TrackingNumber = trackingNumber
	this.PossibleLocation = possibleLocation
	this.PackageDescription = packageDescription
	this.ScopeOfWork = scopeOfWork
	return &this
}

// NewLocatePackageRequestServiceDetailsWithDefaults instantiates a new LocatePackageRequestServiceDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocatePackageRequestServiceDetailsWithDefaults() *LocatePackageRequestServiceDetails {
	this := LocatePackageRequestServiceDetails{}
	return &this
}

// GetShipmentOrderNumber returns the ShipmentOrderNumber field value
func (o *LocatePackageRequestServiceDetails) GetShipmentOrderNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipmentOrderNumber
}

// GetShipmentOrderNumberOk returns a tuple with the ShipmentOrderNumber field value
// and a boolean to check if the value has been set.
func (o *LocatePackageRequestServiceDetails) GetShipmentOrderNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentOrderNumber, true
}

// SetShipmentOrderNumber sets field value
func (o *LocatePackageRequestServiceDetails) SetShipmentOrderNumber(v string) {
	o.ShipmentOrderNumber = v
}

// GetTrackingNumber returns the TrackingNumber field value
func (o *LocatePackageRequestServiceDetails) GetTrackingNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value
// and a boolean to check if the value has been set.
func (o *LocatePackageRequestServiceDetails) GetTrackingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingNumber, true
}

// SetTrackingNumber sets field value
func (o *LocatePackageRequestServiceDetails) SetTrackingNumber(v string) {
	o.TrackingNumber = v
}

// GetPossibleLocation returns the PossibleLocation field value
func (o *LocatePackageRequestServiceDetails) GetPossibleLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PossibleLocation
}

// GetPossibleLocationOk returns a tuple with the PossibleLocation field value
// and a boolean to check if the value has been set.
func (o *LocatePackageRequestServiceDetails) GetPossibleLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PossibleLocation, true
}

// SetPossibleLocation sets field value
func (o *LocatePackageRequestServiceDetails) SetPossibleLocation(v string) {
	o.PossibleLocation = v
}

// GetPackageDescription returns the PackageDescription field value
func (o *LocatePackageRequestServiceDetails) GetPackageDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PackageDescription
}

// GetPackageDescriptionOk returns a tuple with the PackageDescription field value
// and a boolean to check if the value has been set.
func (o *LocatePackageRequestServiceDetails) GetPackageDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PackageDescription, true
}

// SetPackageDescription sets field value
func (o *LocatePackageRequestServiceDetails) SetPackageDescription(v string) {
	o.PackageDescription = v
}

// GetScopeOfWork returns the ScopeOfWork field value
func (o *LocatePackageRequestServiceDetails) GetScopeOfWork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeOfWork
}

// GetScopeOfWorkOk returns a tuple with the ScopeOfWork field value
// and a boolean to check if the value has been set.
func (o *LocatePackageRequestServiceDetails) GetScopeOfWorkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeOfWork, true
}

// SetScopeOfWork sets field value
func (o *LocatePackageRequestServiceDetails) SetScopeOfWork(v string) {
	o.ScopeOfWork = v
}

func (o LocatePackageRequestServiceDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocatePackageRequestServiceDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["shipmentOrderNumber"] = o.ShipmentOrderNumber
	toSerialize["trackingNumber"] = o.TrackingNumber
	toSerialize["possibleLocation"] = o.PossibleLocation
	toSerialize["packageDescription"] = o.PackageDescription
	toSerialize["scopeOfWork"] = o.ScopeOfWork

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LocatePackageRequestServiceDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"shipmentOrderNumber",
		"trackingNumber",
		"possibleLocation",
		"packageDescription",
		"scopeOfWork",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocatePackageRequestServiceDetails := _LocatePackageRequestServiceDetails{}

	err = json.Unmarshal(data, &varLocatePackageRequestServiceDetails)

	if err != nil {
		return err
	}

	*o = LocatePackageRequestServiceDetails(varLocatePackageRequestServiceDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "shipmentOrderNumber")
		delete(additionalProperties, "trackingNumber")
		delete(additionalProperties, "possibleLocation")
		delete(additionalProperties, "packageDescription")
		delete(additionalProperties, "scopeOfWork")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLocatePackageRequestServiceDetails struct {
	value *LocatePackageRequestServiceDetails
	isSet bool
}

func (v NullableLocatePackageRequestServiceDetails) Get() *LocatePackageRequestServiceDetails {
	return v.value
}

func (v *NullableLocatePackageRequestServiceDetails) Set(val *LocatePackageRequestServiceDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableLocatePackageRequestServiceDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableLocatePackageRequestServiceDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocatePackageRequestServiceDetails(val *LocatePackageRequestServiceDetails) *NullableLocatePackageRequestServiceDetails {
	return &NullableLocatePackageRequestServiceDetails{value: val, isSet: true}
}

func (v NullableLocatePackageRequestServiceDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocatePackageRequestServiceDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
