name: Test __PACKAGE_NAME__ codegen

on:
  push:
    paths:
    - "**/__PACKAGE_NAME__/**"
  pull_request:
    paths:
    - "**/__PACKAGE_NAME__/**"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Verify Patches
      run: make -f Makefile.__PACKAGE_NAME__ patch
    - name: Generate
      run: |
        make -f Makefile.__PACKAGE_NAME__ generate
        # Expect all changes to be accounted for
        ! git status --porcelain | grep .
