/*
Equinix Fabric API v4

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the RouteFiltersSearchFilterItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouteFiltersSearchFilterItem{}

// RouteFiltersSearchFilterItem struct for RouteFiltersSearchFilterItem
type RouteFiltersSearchFilterItem struct {
	Property             *RouteFiltersSearchFilterItemProperty `json:"property,omitempty"`
	Operator             *string                               `json:"operator,omitempty"`
	Values               []string                              `json:"values,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RouteFiltersSearchFilterItem RouteFiltersSearchFilterItem

// NewRouteFiltersSearchFilterItem instantiates a new RouteFiltersSearchFilterItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouteFiltersSearchFilterItem() *RouteFiltersSearchFilterItem {
	this := RouteFiltersSearchFilterItem{}
	return &this
}

// NewRouteFiltersSearchFilterItemWithDefaults instantiates a new RouteFiltersSearchFilterItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteFiltersSearchFilterItemWithDefaults() *RouteFiltersSearchFilterItem {
	this := RouteFiltersSearchFilterItem{}
	return &this
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *RouteFiltersSearchFilterItem) GetProperty() RouteFiltersSearchFilterItemProperty {
	if o == nil || IsNil(o.Property) {
		var ret RouteFiltersSearchFilterItemProperty
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteFiltersSearchFilterItem) GetPropertyOk() (*RouteFiltersSearchFilterItemProperty, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *RouteFiltersSearchFilterItem) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given RouteFiltersSearchFilterItemProperty and assigns it to the Property field.
func (o *RouteFiltersSearchFilterItem) SetProperty(v RouteFiltersSearchFilterItemProperty) {
	o.Property = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *RouteFiltersSearchFilterItem) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteFiltersSearchFilterItem) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *RouteFiltersSearchFilterItem) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *RouteFiltersSearchFilterItem) SetOperator(v string) {
	o.Operator = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *RouteFiltersSearchFilterItem) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteFiltersSearchFilterItem) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *RouteFiltersSearchFilterItem) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *RouteFiltersSearchFilterItem) SetValues(v []string) {
	o.Values = v
}

func (o RouteFiltersSearchFilterItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouteFiltersSearchFilterItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RouteFiltersSearchFilterItem) UnmarshalJSON(data []byte) (err error) {
	varRouteFiltersSearchFilterItem := _RouteFiltersSearchFilterItem{}

	err = json.Unmarshal(data, &varRouteFiltersSearchFilterItem)

	if err != nil {
		return err
	}

	*o = RouteFiltersSearchFilterItem(varRouteFiltersSearchFilterItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "property")
		delete(additionalProperties, "operator")
		delete(additionalProperties, "values")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRouteFiltersSearchFilterItem struct {
	value *RouteFiltersSearchFilterItem
	isSet bool
}

func (v NullableRouteFiltersSearchFilterItem) Get() *RouteFiltersSearchFilterItem {
	return v.value
}

func (v *NullableRouteFiltersSearchFilterItem) Set(val *RouteFiltersSearchFilterItem) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteFiltersSearchFilterItem) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteFiltersSearchFilterItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteFiltersSearchFilterItem(val *RouteFiltersSearchFilterItem) *NullableRouteFiltersSearchFilterItem {
	return &NullableRouteFiltersSearchFilterItem{value: val, isSet: true}
}

func (v NullableRouteFiltersSearchFilterItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteFiltersSearchFilterItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
