/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// CloudRouterActionsSearchSortDirection Sorting direction
type CloudRouterActionsSearchSortDirection string

// List of CloudRouterActionsSearchSortDirection
const (
	CLOUDROUTERACTIONSSEARCHSORTDIRECTION_DESC CloudRouterActionsSearchSortDirection = "DESC"
	CLOUDROUTERACTIONSSEARCHSORTDIRECTION_ASC  CloudRouterActionsSearchSortDirection = "ASC"
)

// All allowed values of CloudRouterActionsSearchSortDirection enum
var AllowedCloudRouterActionsSearchSortDirectionEnumValues = []CloudRouterActionsSearchSortDirection{
	"DESC",
	"ASC",
}

func (v *CloudRouterActionsSearchSortDirection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CloudRouterActionsSearchSortDirection(value)
	for _, existing := range AllowedCloudRouterActionsSearchSortDirectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CloudRouterActionsSearchSortDirection", value)
}

// NewCloudRouterActionsSearchSortDirectionFromValue returns a pointer to a valid CloudRouterActionsSearchSortDirection
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCloudRouterActionsSearchSortDirectionFromValue(v string) (*CloudRouterActionsSearchSortDirection, error) {
	ev := CloudRouterActionsSearchSortDirection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CloudRouterActionsSearchSortDirection: valid values are %v", v, AllowedCloudRouterActionsSearchSortDirectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CloudRouterActionsSearchSortDirection) IsValid() bool {
	for _, existing := range AllowedCloudRouterActionsSearchSortDirectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CloudRouterActionsSearchSortDirection value
func (v CloudRouterActionsSearchSortDirection) Ptr() *CloudRouterActionsSearchSortDirection {
	return &v
}

type NullableCloudRouterActionsSearchSortDirection struct {
	value *CloudRouterActionsSearchSortDirection
	isSet bool
}

func (v NullableCloudRouterActionsSearchSortDirection) Get() *CloudRouterActionsSearchSortDirection {
	return v.value
}

func (v *NullableCloudRouterActionsSearchSortDirection) Set(val *CloudRouterActionsSearchSortDirection) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudRouterActionsSearchSortDirection) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudRouterActionsSearchSortDirection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudRouterActionsSearchSortDirection(val *CloudRouterActionsSearchSortDirection) *NullableCloudRouterActionsSearchSortDirection {
	return &NullableCloudRouterActionsSearchSortDirection{value: val, isSet: true}
}

func (v NullableCloudRouterActionsSearchSortDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudRouterActionsSearchSortDirection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
