/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the LoaSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoaSearchResponse{}

// LoaSearchResponse List of LOAs
type LoaSearchResponse struct {
	Pagination           *Pagination       `json:"pagination,omitempty"`
	Sort                 []LoaSortCriteria `json:"sort,omitempty"`
	Data                 []LoaResponse     `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LoaSearchResponse LoaSearchResponse

// NewLoaSearchResponse instantiates a new LoaSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoaSearchResponse() *LoaSearchResponse {
	this := LoaSearchResponse{}
	return &this
}

// NewLoaSearchResponseWithDefaults instantiates a new LoaSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoaSearchResponseWithDefaults() *LoaSearchResponse {
	this := LoaSearchResponse{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *LoaSearchResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoaSearchResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *LoaSearchResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *LoaSearchResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *LoaSearchResponse) GetSort() []LoaSortCriteria {
	if o == nil || IsNil(o.Sort) {
		var ret []LoaSortCriteria
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoaSearchResponse) GetSortOk() ([]LoaSortCriteria, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *LoaSearchResponse) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []LoaSortCriteria and assigns it to the Sort field.
func (o *LoaSearchResponse) SetSort(v []LoaSortCriteria) {
	o.Sort = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LoaSearchResponse) GetData() []LoaResponse {
	if o == nil || IsNil(o.Data) {
		var ret []LoaResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoaSearchResponse) GetDataOk() ([]LoaResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LoaSearchResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []LoaResponse and assigns it to the Data field.
func (o *LoaSearchResponse) SetData(v []LoaResponse) {
	o.Data = v
}

func (o LoaSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoaSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoaSearchResponse) UnmarshalJSON(data []byte) (err error) {
	varLoaSearchResponse := _LoaSearchResponse{}

	err = json.Unmarshal(data, &varLoaSearchResponse)

	if err != nil {
		return err
	}

	*o = LoaSearchResponse(varLoaSearchResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "sort")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoaSearchResponse struct {
	value *LoaSearchResponse
	isSet bool
}

func (v NullableLoaSearchResponse) Get() *LoaSearchResponse {
	return v.value
}

func (v *NullableLoaSearchResponse) Set(val *LoaSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLoaSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLoaSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoaSearchResponse(val *LoaSearchResponse) *NullableLoaSearchResponse {
	return &NullableLoaSearchResponse{value: val, isSet: true}
}

func (v NullableLoaSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoaSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
