/*
Equinix Fabric API v4

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ConnectionSideAdditionalInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionSideAdditionalInfo{}

// ConnectionSideAdditionalInfo Additional information
type ConnectionSideAdditionalInfo struct {
	// Key
	Key *string `json:"key,omitempty"`
	// Value
	Value                *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionSideAdditionalInfo ConnectionSideAdditionalInfo

// NewConnectionSideAdditionalInfo instantiates a new ConnectionSideAdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionSideAdditionalInfo() *ConnectionSideAdditionalInfo {
	this := ConnectionSideAdditionalInfo{}
	return &this
}

// NewConnectionSideAdditionalInfoWithDefaults instantiates a new ConnectionSideAdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionSideAdditionalInfoWithDefaults() *ConnectionSideAdditionalInfo {
	this := ConnectionSideAdditionalInfo{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ConnectionSideAdditionalInfo) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionSideAdditionalInfo) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ConnectionSideAdditionalInfo) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ConnectionSideAdditionalInfo) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ConnectionSideAdditionalInfo) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionSideAdditionalInfo) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ConnectionSideAdditionalInfo) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ConnectionSideAdditionalInfo) SetValue(v string) {
	o.Value = &v
}

func (o ConnectionSideAdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionSideAdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionSideAdditionalInfo) UnmarshalJSON(data []byte) (err error) {
	varConnectionSideAdditionalInfo := _ConnectionSideAdditionalInfo{}

	err = json.Unmarshal(data, &varConnectionSideAdditionalInfo)

	if err != nil {
		return err
	}

	*o = ConnectionSideAdditionalInfo(varConnectionSideAdditionalInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionSideAdditionalInfo struct {
	value *ConnectionSideAdditionalInfo
	isSet bool
}

func (v NullableConnectionSideAdditionalInfo) Get() *ConnectionSideAdditionalInfo {
	return v.value
}

func (v *NullableConnectionSideAdditionalInfo) Set(val *ConnectionSideAdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionSideAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionSideAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionSideAdditionalInfo(val *ConnectionSideAdditionalInfo) *NullableConnectionSideAdditionalInfo {
	return &NullableConnectionSideAdditionalInfo{value: val, isSet: true}
}

func (v NullableConnectionSideAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionSideAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
