/*
Equinix Fabric API v4

Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CloudRouterChange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudRouterChange{}

// CloudRouterChange Current state of latest CloudRouter change
type CloudRouterChange struct {
	// Uniquely identifies a change
	Uuid   *string                  `json:"uuid,omitempty"`
	Type   CloudRouterChangeType    `json:"type"`
	Status *CloudRouterChangeStatus `json:"status,omitempty"`
	// Set when change flow starts
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// Set when change object is updated
	UpdatedDateTime time.Time `json:"updatedDateTime"`
	// Additional information
	Information          *string                     `json:"information,omitempty"`
	Data                 *CloudRouterChangeOperation `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CloudRouterChange CloudRouterChange

// NewCloudRouterChange instantiates a new CloudRouterChange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudRouterChange(type_ CloudRouterChangeType, updatedDateTime time.Time) *CloudRouterChange {
	this := CloudRouterChange{}
	this.Type = type_
	this.UpdatedDateTime = updatedDateTime
	return &this
}

// NewCloudRouterChangeWithDefaults instantiates a new CloudRouterChange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudRouterChangeWithDefaults() *CloudRouterChange {
	this := CloudRouterChange{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *CloudRouterChange) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *CloudRouterChange) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *CloudRouterChange) SetUuid(v string) {
	o.Uuid = &v
}

// GetType returns the Type field value
func (o *CloudRouterChange) GetType() CloudRouterChangeType {
	if o == nil {
		var ret CloudRouterChangeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetTypeOk() (*CloudRouterChangeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CloudRouterChange) SetType(v CloudRouterChangeType) {
	o.Type = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CloudRouterChange) GetStatus() CloudRouterChangeStatus {
	if o == nil || IsNil(o.Status) {
		var ret CloudRouterChangeStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetStatusOk() (*CloudRouterChangeStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CloudRouterChange) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CloudRouterChangeStatus and assigns it to the Status field.
func (o *CloudRouterChange) SetStatus(v CloudRouterChangeStatus) {
	o.Status = &v
}

// GetCreatedDateTime returns the CreatedDateTime field value if set, zero value otherwise.
func (o *CloudRouterChange) GetCreatedDateTime() time.Time {
	if o == nil || IsNil(o.CreatedDateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDateTime
}

// GetCreatedDateTimeOk returns a tuple with the CreatedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetCreatedDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDateTime) {
		return nil, false
	}
	return o.CreatedDateTime, true
}

// HasCreatedDateTime returns a boolean if a field has been set.
func (o *CloudRouterChange) HasCreatedDateTime() bool {
	if o != nil && !IsNil(o.CreatedDateTime) {
		return true
	}

	return false
}

// SetCreatedDateTime gets a reference to the given time.Time and assigns it to the CreatedDateTime field.
func (o *CloudRouterChange) SetCreatedDateTime(v time.Time) {
	o.CreatedDateTime = &v
}

// GetUpdatedDateTime returns the UpdatedDateTime field value
func (o *CloudRouterChange) GetUpdatedDateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedDateTime
}

// GetUpdatedDateTimeOk returns a tuple with the UpdatedDateTime field value
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetUpdatedDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedDateTime, true
}

// SetUpdatedDateTime sets field value
func (o *CloudRouterChange) SetUpdatedDateTime(v time.Time) {
	o.UpdatedDateTime = v
}

// GetInformation returns the Information field value if set, zero value otherwise.
func (o *CloudRouterChange) GetInformation() string {
	if o == nil || IsNil(o.Information) {
		var ret string
		return ret
	}
	return *o.Information
}

// GetInformationOk returns a tuple with the Information field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetInformationOk() (*string, bool) {
	if o == nil || IsNil(o.Information) {
		return nil, false
	}
	return o.Information, true
}

// HasInformation returns a boolean if a field has been set.
func (o *CloudRouterChange) HasInformation() bool {
	if o != nil && !IsNil(o.Information) {
		return true
	}

	return false
}

// SetInformation gets a reference to the given string and assigns it to the Information field.
func (o *CloudRouterChange) SetInformation(v string) {
	o.Information = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CloudRouterChange) GetData() CloudRouterChangeOperation {
	if o == nil || IsNil(o.Data) {
		var ret CloudRouterChangeOperation
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudRouterChange) GetDataOk() (*CloudRouterChangeOperation, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CloudRouterChange) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CloudRouterChangeOperation and assigns it to the Data field.
func (o *CloudRouterChange) SetData(v CloudRouterChangeOperation) {
	o.Data = &v
}

func (o CloudRouterChange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudRouterChange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CreatedDateTime) {
		toSerialize["createdDateTime"] = o.CreatedDateTime
	}
	toSerialize["updatedDateTime"] = o.UpdatedDateTime
	if !IsNil(o.Information) {
		toSerialize["information"] = o.Information
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CloudRouterChange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"updatedDateTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudRouterChange := _CloudRouterChange{}

	err = json.Unmarshal(data, &varCloudRouterChange)

	if err != nil {
		return err
	}

	*o = CloudRouterChange(varCloudRouterChange)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "type")
		delete(additionalProperties, "status")
		delete(additionalProperties, "createdDateTime")
		delete(additionalProperties, "updatedDateTime")
		delete(additionalProperties, "information")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCloudRouterChange struct {
	value *CloudRouterChange
	isSet bool
}

func (v NullableCloudRouterChange) Get() *CloudRouterChange {
	return v.value
}

func (v *NullableCloudRouterChange) Set(val *CloudRouterChange) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudRouterChange) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudRouterChange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudRouterChange(val *CloudRouterChange) *NullableCloudRouterChange {
	return &NullableCloudRouterChange{value: val, isSet: true}
}

func (v NullableCloudRouterChange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudRouterChange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
