/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the CloudEventFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudEventFilters{}

// CloudEventFilters struct for CloudEventFilters
type CloudEventFilters struct {
	And                  []CloudEventSimpleExpression `json:"and,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CloudEventFilters CloudEventFilters

// NewCloudEventFilters instantiates a new CloudEventFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudEventFilters() *CloudEventFilters {
	this := CloudEventFilters{}
	return &this
}

// NewCloudEventFiltersWithDefaults instantiates a new CloudEventFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudEventFiltersWithDefaults() *CloudEventFilters {
	this := CloudEventFilters{}
	return &this
}

// GetAnd returns the And field value if set, zero value otherwise.
func (o *CloudEventFilters) GetAnd() []CloudEventSimpleExpression {
	if o == nil || IsNil(o.And) {
		var ret []CloudEventSimpleExpression
		return ret
	}
	return o.And
}

// GetAndOk returns a tuple with the And field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudEventFilters) GetAndOk() ([]CloudEventSimpleExpression, bool) {
	if o == nil || IsNil(o.And) {
		return nil, false
	}
	return o.And, true
}

// HasAnd returns a boolean if a field has been set.
func (o *CloudEventFilters) HasAnd() bool {
	if o != nil && !IsNil(o.And) {
		return true
	}

	return false
}

// SetAnd gets a reference to the given []CloudEventSimpleExpression and assigns it to the And field.
func (o *CloudEventFilters) SetAnd(v []CloudEventSimpleExpression) {
	o.And = v
}

func (o CloudEventFilters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudEventFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.And) {
		toSerialize["and"] = o.And
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CloudEventFilters) UnmarshalJSON(data []byte) (err error) {
	varCloudEventFilters := _CloudEventFilters{}

	err = json.Unmarshal(data, &varCloudEventFilters)

	if err != nil {
		return err
	}

	*o = CloudEventFilters(varCloudEventFilters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "and")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCloudEventFilters struct {
	value *CloudEventFilters
	isSet bool
}

func (v NullableCloudEventFilters) Get() *CloudEventFilters {
	return v.value
}

func (v *NullableCloudEventFilters) Set(val *CloudEventFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudEventFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudEventFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudEventFilters(val *CloudEventFilters) *NullableCloudEventFilters {
	return &NullableCloudEventFilters{value: val, isSet: true}
}

func (v NullableCloudEventFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudEventFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
