/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// checks if the IpBlockLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpBlockLocation{}

// IpBlockLocation struct for IpBlockLocation
type IpBlockLocation struct {
	// Metro URL path for the linked resource
	MetroHref            *string `json:"metroHref,omitempty"`
	MetroCode            string  `json:"metroCode" validate:"regexp=^[A-Z]{2}$"`
	AdditionalProperties map[string]interface{}
}

type _IpBlockLocation IpBlockLocation

// NewIpBlockLocation instantiates a new IpBlockLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpBlockLocation(metroCode string) *IpBlockLocation {
	this := IpBlockLocation{}
	this.MetroCode = metroCode
	return &this
}

// NewIpBlockLocationWithDefaults instantiates a new IpBlockLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpBlockLocationWithDefaults() *IpBlockLocation {
	this := IpBlockLocation{}
	return &this
}

// GetMetroHref returns the MetroHref field value if set, zero value otherwise.
func (o *IpBlockLocation) GetMetroHref() string {
	if o == nil || IsNil(o.MetroHref) {
		var ret string
		return ret
	}
	return *o.MetroHref
}

// GetMetroHrefOk returns a tuple with the MetroHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockLocation) GetMetroHrefOk() (*string, bool) {
	if o == nil || IsNil(o.MetroHref) {
		return nil, false
	}
	return o.MetroHref, true
}

// HasMetroHref returns a boolean if a field has been set.
func (o *IpBlockLocation) HasMetroHref() bool {
	if o != nil && !IsNil(o.MetroHref) {
		return true
	}

	return false
}

// SetMetroHref gets a reference to the given string and assigns it to the MetroHref field.
func (o *IpBlockLocation) SetMetroHref(v string) {
	o.MetroHref = &v
}

// GetMetroCode returns the MetroCode field value
func (o *IpBlockLocation) GetMetroCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetroCode
}

// GetMetroCodeOk returns a tuple with the MetroCode field value
// and a boolean to check if the value has been set.
func (o *IpBlockLocation) GetMetroCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetroCode, true
}

// SetMetroCode sets field value
func (o *IpBlockLocation) SetMetroCode(v string) {
	o.MetroCode = v
}

func (o IpBlockLocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpBlockLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetroHref) {
		toSerialize["metroHref"] = o.MetroHref
	}
	toSerialize["metroCode"] = o.MetroCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IpBlockLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metroCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpBlockLocation := _IpBlockLocation{}

	err = json.Unmarshal(data, &varIpBlockLocation)

	if err != nil {
		return err
	}

	*o = IpBlockLocation(varIpBlockLocation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "metroHref")
		delete(additionalProperties, "metroCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIpBlockLocation struct {
	value *IpBlockLocation
	isSet bool
}

func (v NullableIpBlockLocation) Get() *IpBlockLocation {
	return v.value
}

func (v *NullableIpBlockLocation) Set(val *IpBlockLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableIpBlockLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableIpBlockLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpBlockLocation(val *IpBlockLocation) *NullableIpBlockLocation {
	return &NullableIpBlockLocation{value: val, isSet: true}
}

func (v NullableIpBlockLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpBlockLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
