/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the Interconnect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Interconnect{}

// Interconnect Interconnect specification <font color=\"red\"> <sup color='red'>Beta</sup></font>
type Interconnect struct {
	// Interconnect URI
	Href *string `json:"href,omitempty"`
	// Equinix-assigned interconnect identifier
	Uuid *string                      `json:"uuid,omitempty"`
	Type *InterconnectPostRequestType `json:"type,omitempty"`
	// Interconnect name
	Name *string `json:"name,omitempty"`
	// Interconnect description
	Description *string               `json:"description,omitempty"`
	State       *InterconnectState    `json:"state,omitempty"`
	Location    *InterconnectLocation `json:"location,omitempty"`
	// Interconnect used bandwidth in Mbps
	UsedBandwidth *int32               `json:"usedBandwidth,omitempty"`
	Package       *InterconnectPackage `json:"package,omitempty"`
	Router        *InterconnectRouter  `json:"router,omitempty"`
	Order         *Order               `json:"order,omitempty"`
	Account       *SimplifiedAccount   `json:"account,omitempty"`
	Project       *Project             `json:"project,omitempty"`
	// Interconnect notification preferences
	Notifications        []InterconnectNotification `json:"notifications,omitempty"`
	ChangeLog            *Changelog                 `json:"changeLog,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Interconnect Interconnect

// NewInterconnect instantiates a new Interconnect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterconnect() *Interconnect {
	this := Interconnect{}
	return &this
}

// NewInterconnectWithDefaults instantiates a new Interconnect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterconnectWithDefaults() *Interconnect {
	this := Interconnect{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Interconnect) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Interconnect) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Interconnect) SetHref(v string) {
	o.Href = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *Interconnect) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *Interconnect) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *Interconnect) SetUuid(v string) {
	o.Uuid = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Interconnect) GetType() InterconnectPostRequestType {
	if o == nil || IsNil(o.Type) {
		var ret InterconnectPostRequestType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetTypeOk() (*InterconnectPostRequestType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Interconnect) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given InterconnectPostRequestType and assigns it to the Type field.
func (o *Interconnect) SetType(v InterconnectPostRequestType) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Interconnect) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Interconnect) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Interconnect) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Interconnect) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Interconnect) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Interconnect) SetDescription(v string) {
	o.Description = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *Interconnect) GetState() InterconnectState {
	if o == nil || IsNil(o.State) {
		var ret InterconnectState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetStateOk() (*InterconnectState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *Interconnect) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given InterconnectState and assigns it to the State field.
func (o *Interconnect) SetState(v InterconnectState) {
	o.State = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Interconnect) GetLocation() InterconnectLocation {
	if o == nil || IsNil(o.Location) {
		var ret InterconnectLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetLocationOk() (*InterconnectLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Interconnect) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given InterconnectLocation and assigns it to the Location field.
func (o *Interconnect) SetLocation(v InterconnectLocation) {
	o.Location = &v
}

// GetUsedBandwidth returns the UsedBandwidth field value if set, zero value otherwise.
func (o *Interconnect) GetUsedBandwidth() int32 {
	if o == nil || IsNil(o.UsedBandwidth) {
		var ret int32
		return ret
	}
	return *o.UsedBandwidth
}

// GetUsedBandwidthOk returns a tuple with the UsedBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetUsedBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.UsedBandwidth) {
		return nil, false
	}
	return o.UsedBandwidth, true
}

// HasUsedBandwidth returns a boolean if a field has been set.
func (o *Interconnect) HasUsedBandwidth() bool {
	if o != nil && !IsNil(o.UsedBandwidth) {
		return true
	}

	return false
}

// SetUsedBandwidth gets a reference to the given int32 and assigns it to the UsedBandwidth field.
func (o *Interconnect) SetUsedBandwidth(v int32) {
	o.UsedBandwidth = &v
}

// GetPackage returns the Package field value if set, zero value otherwise.
func (o *Interconnect) GetPackage() InterconnectPackage {
	if o == nil || IsNil(o.Package) {
		var ret InterconnectPackage
		return ret
	}
	return *o.Package
}

// GetPackageOk returns a tuple with the Package field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetPackageOk() (*InterconnectPackage, bool) {
	if o == nil || IsNil(o.Package) {
		return nil, false
	}
	return o.Package, true
}

// HasPackage returns a boolean if a field has been set.
func (o *Interconnect) HasPackage() bool {
	if o != nil && !IsNil(o.Package) {
		return true
	}

	return false
}

// SetPackage gets a reference to the given InterconnectPackage and assigns it to the Package field.
func (o *Interconnect) SetPackage(v InterconnectPackage) {
	o.Package = &v
}

// GetRouter returns the Router field value if set, zero value otherwise.
func (o *Interconnect) GetRouter() InterconnectRouter {
	if o == nil || IsNil(o.Router) {
		var ret InterconnectRouter
		return ret
	}
	return *o.Router
}

// GetRouterOk returns a tuple with the Router field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetRouterOk() (*InterconnectRouter, bool) {
	if o == nil || IsNil(o.Router) {
		return nil, false
	}
	return o.Router, true
}

// HasRouter returns a boolean if a field has been set.
func (o *Interconnect) HasRouter() bool {
	if o != nil && !IsNil(o.Router) {
		return true
	}

	return false
}

// SetRouter gets a reference to the given InterconnectRouter and assigns it to the Router field.
func (o *Interconnect) SetRouter(v InterconnectRouter) {
	o.Router = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Interconnect) GetOrder() Order {
	if o == nil || IsNil(o.Order) {
		var ret Order
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetOrderOk() (*Order, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Interconnect) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given Order and assigns it to the Order field.
func (o *Interconnect) SetOrder(v Order) {
	o.Order = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *Interconnect) GetAccount() SimplifiedAccount {
	if o == nil || IsNil(o.Account) {
		var ret SimplifiedAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetAccountOk() (*SimplifiedAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *Interconnect) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given SimplifiedAccount and assigns it to the Account field.
func (o *Interconnect) SetAccount(v SimplifiedAccount) {
	o.Account = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *Interconnect) GetProject() Project {
	if o == nil || IsNil(o.Project) {
		var ret Project
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetProjectOk() (*Project, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *Interconnect) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given Project and assigns it to the Project field.
func (o *Interconnect) SetProject(v Project) {
	o.Project = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *Interconnect) GetNotifications() []InterconnectNotification {
	if o == nil || IsNil(o.Notifications) {
		var ret []InterconnectNotification
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetNotificationsOk() ([]InterconnectNotification, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *Interconnect) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []InterconnectNotification and assigns it to the Notifications field.
func (o *Interconnect) SetNotifications(v []InterconnectNotification) {
	o.Notifications = v
}

// GetChangeLog returns the ChangeLog field value if set, zero value otherwise.
func (o *Interconnect) GetChangeLog() Changelog {
	if o == nil || IsNil(o.ChangeLog) {
		var ret Changelog
		return ret
	}
	return *o.ChangeLog
}

// GetChangeLogOk returns a tuple with the ChangeLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interconnect) GetChangeLogOk() (*Changelog, bool) {
	if o == nil || IsNil(o.ChangeLog) {
		return nil, false
	}
	return o.ChangeLog, true
}

// HasChangeLog returns a boolean if a field has been set.
func (o *Interconnect) HasChangeLog() bool {
	if o != nil && !IsNil(o.ChangeLog) {
		return true
	}

	return false
}

// SetChangeLog gets a reference to the given Changelog and assigns it to the ChangeLog field.
func (o *Interconnect) SetChangeLog(v Changelog) {
	o.ChangeLog = &v
}

func (o Interconnect) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Interconnect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.UsedBandwidth) {
		toSerialize["usedBandwidth"] = o.UsedBandwidth
	}
	if !IsNil(o.Package) {
		toSerialize["package"] = o.Package
	}
	if !IsNil(o.Router) {
		toSerialize["router"] = o.Router
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.ChangeLog) {
		toSerialize["changeLog"] = o.ChangeLog
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Interconnect) UnmarshalJSON(data []byte) (err error) {
	varInterconnect := _Interconnect{}

	err = json.Unmarshal(data, &varInterconnect)

	if err != nil {
		return err
	}

	*o = Interconnect(varInterconnect)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "state")
		delete(additionalProperties, "location")
		delete(additionalProperties, "usedBandwidth")
		delete(additionalProperties, "package")
		delete(additionalProperties, "router")
		delete(additionalProperties, "order")
		delete(additionalProperties, "account")
		delete(additionalProperties, "project")
		delete(additionalProperties, "notifications")
		delete(additionalProperties, "changeLog")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInterconnect struct {
	value *Interconnect
	isSet bool
}

func (v NullableInterconnect) Get() *Interconnect {
	return v.value
}

func (v *NullableInterconnect) Set(val *Interconnect) {
	v.value = val
	v.isSet = true
}

func (v NullableInterconnect) IsSet() bool {
	return v.isSet
}

func (v *NullableInterconnect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterconnect(val *Interconnect) *NullableInterconnect {
	return &NullableInterconnect{value: val, isSet: true}
}

func (v NullableInterconnect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterconnect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
