/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ConnectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionResponse{}

// ConnectionResponse ValidateResponse
type ConnectionResponse struct {
	// Additional information
	AdditionalInfo []ConnectionSideAdditionalInfo `json:"additionalInfo,omitempty"`
	// Connection response data
	Data                 []ValidateConnectionResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionResponse ConnectionResponse

// NewConnectionResponse instantiates a new ConnectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionResponse() *ConnectionResponse {
	this := ConnectionResponse{}
	return &this
}

// NewConnectionResponseWithDefaults instantiates a new ConnectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionResponseWithDefaults() *ConnectionResponse {
	this := ConnectionResponse{}
	return &this
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *ConnectionResponse) GetAdditionalInfo() []ConnectionSideAdditionalInfo {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret []ConnectionSideAdditionalInfo
		return ret
	}
	return o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionResponse) GetAdditionalInfoOk() ([]ConnectionSideAdditionalInfo, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *ConnectionResponse) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given []ConnectionSideAdditionalInfo and assigns it to the AdditionalInfo field.
func (o *ConnectionResponse) SetAdditionalInfo(v []ConnectionSideAdditionalInfo) {
	o.AdditionalInfo = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ConnectionResponse) GetData() []ValidateConnectionResponse {
	if o == nil || IsNil(o.Data) {
		var ret []ValidateConnectionResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionResponse) GetDataOk() ([]ValidateConnectionResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ConnectionResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ValidateConnectionResponse and assigns it to the Data field.
func (o *ConnectionResponse) SetData(v []ValidateConnectionResponse) {
	o.Data = v
}

func (o ConnectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionResponse) UnmarshalJSON(data []byte) (err error) {
	varConnectionResponse := _ConnectionResponse{}

	err = json.Unmarshal(data, &varConnectionResponse)

	if err != nil {
		return err
	}

	*o = ConnectionResponse(varConnectionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "additionalInfo")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionResponse struct {
	value *ConnectionResponse
	isSet bool
}

func (v NullableConnectionResponse) Get() *ConnectionResponse {
	return v.value
}

func (v *NullableConnectionResponse) Set(val *ConnectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionResponse(val *ConnectionResponse) *NullableConnectionResponse {
	return &NullableConnectionResponse{value: val, isSet: true}
}

func (v NullableConnectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
