/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// AttachedAppServiceOrder Sort order for attached App Services.
type AttachedAppServiceOrder string

// List of AttachedAppServiceOrder
const (
	ATTACHEDAPPSERVICEORDER_DESC AttachedAppServiceOrder = "DESC"
	ATTACHEDAPPSERVICEORDER_ASC  AttachedAppServiceOrder = "ASC"
)

// All allowed values of AttachedAppServiceOrder enum
var AllowedAttachedAppServiceOrderEnumValues = []AttachedAppServiceOrder{
	"DESC",
	"ASC",
}

func (v *AttachedAppServiceOrder) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AttachedAppServiceOrder(value)
	for _, existing := range AllowedAttachedAppServiceOrderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AttachedAppServiceOrder", value)
}

// NewAttachedAppServiceOrderFromValue returns a pointer to a valid AttachedAppServiceOrder
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAttachedAppServiceOrderFromValue(v string) (*AttachedAppServiceOrder, error) {
	ev := AttachedAppServiceOrder(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AttachedAppServiceOrder: valid values are %v", v, AllowedAttachedAppServiceOrderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AttachedAppServiceOrder) IsValid() bool {
	for _, existing := range AllowedAttachedAppServiceOrderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AttachedAppServiceOrder value
func (v AttachedAppServiceOrder) Ptr() *AttachedAppServiceOrder {
	return &v
}

type NullableAttachedAppServiceOrder struct {
	value *AttachedAppServiceOrder
	isSet bool
}

func (v NullableAttachedAppServiceOrder) Get() *AttachedAppServiceOrder {
	return v.value
}

func (v *NullableAttachedAppServiceOrder) Set(val *AttachedAppServiceOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachedAppServiceOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachedAppServiceOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachedAppServiceOrder(val *AttachedAppServiceOrder) *NullableAttachedAppServiceOrder {
	return &NullableAttachedAppServiceOrder{value: val, isSet: true}
}

func (v NullableAttachedAppServiceOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachedAppServiceOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
