/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// IpBlockProductType the model 'IpBlockProductType'
type IpBlockProductType string

// List of IpBlockProductType
const (
	IPBLOCKPRODUCTTYPE_EIA    IpBlockProductType = "EIA"
	IPBLOCKPRODUCTTYPE_FABRIC IpBlockProductType = "FABRIC"
	IPBLOCKPRODUCTTYPE_NE     IpBlockProductType = "NE"
)

// All allowed values of IpBlockProductType enum
var AllowedIpBlockProductTypeEnumValues = []IpBlockProductType{
	"EIA",
	"FABRIC",
	"NE",
}

func (v *IpBlockProductType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IpBlockProductType(value)
	for _, existing := range AllowedIpBlockProductTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IpBlockProductType", value)
}

// NewIpBlockProductTypeFromValue returns a pointer to a valid IpBlockProductType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIpBlockProductTypeFromValue(v string) (*IpBlockProductType, error) {
	ev := IpBlockProductType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IpBlockProductType: valid values are %v", v, AllowedIpBlockProductTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IpBlockProductType) IsValid() bool {
	for _, existing := range AllowedIpBlockProductTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IpBlockProductType value
func (v IpBlockProductType) Ptr() *IpBlockProductType {
	return &v
}

type NullableIpBlockProductType struct {
	value *IpBlockProductType
	isSet bool
}

func (v NullableIpBlockProductType) Get() *IpBlockProductType {
	return v.value
}

func (v *NullableIpBlockProductType) Set(val *IpBlockProductType) {
	v.value = val
	v.isSet = true
}

func (v NullableIpBlockProductType) IsSet() bool {
	return v.isSet
}

func (v *NullableIpBlockProductType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpBlockProductType(val *IpBlockProductType) *NullableIpBlockProductType {
	return &NullableIpBlockProductType{value: val, isSet: true}
}

func (v NullableIpBlockProductType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpBlockProductType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
