/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ServiceProfileLastMileProductCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceProfileLastMileProductCatalog{}

// ServiceProfileLastMileProductCatalog Last-mile provider catalog details.
type ServiceProfileLastMileProductCatalog struct {
	// Last-mile provider or catalog name.
	Name *string `json:"name,omitempty"`
	// Last-mile catalog or provider website URL.
	WebUrl       *string                                  `json:"webUrl,omitempty"`
	DeliveryDate *ServiceProfileLastMileDeliveryDateRange `json:"deliveryDate,omitempty"`
	// Available last-mile offerings.
	Offerings            []ServiceProfileLastMileOffering `json:"offerings,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceProfileLastMileProductCatalog ServiceProfileLastMileProductCatalog

// NewServiceProfileLastMileProductCatalog instantiates a new ServiceProfileLastMileProductCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceProfileLastMileProductCatalog() *ServiceProfileLastMileProductCatalog {
	this := ServiceProfileLastMileProductCatalog{}
	return &this
}

// NewServiceProfileLastMileProductCatalogWithDefaults instantiates a new ServiceProfileLastMileProductCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceProfileLastMileProductCatalogWithDefaults() *ServiceProfileLastMileProductCatalog {
	this := ServiceProfileLastMileProductCatalog{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceProfileLastMileProductCatalog) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProfileLastMileProductCatalog) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceProfileLastMileProductCatalog) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceProfileLastMileProductCatalog) SetName(v string) {
	o.Name = &v
}

// GetWebUrl returns the WebUrl field value if set, zero value otherwise.
func (o *ServiceProfileLastMileProductCatalog) GetWebUrl() string {
	if o == nil || IsNil(o.WebUrl) {
		var ret string
		return ret
	}
	return *o.WebUrl
}

// GetWebUrlOk returns a tuple with the WebUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProfileLastMileProductCatalog) GetWebUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebUrl) {
		return nil, false
	}
	return o.WebUrl, true
}

// HasWebUrl returns a boolean if a field has been set.
func (o *ServiceProfileLastMileProductCatalog) HasWebUrl() bool {
	if o != nil && !IsNil(o.WebUrl) {
		return true
	}

	return false
}

// SetWebUrl gets a reference to the given string and assigns it to the WebUrl field.
func (o *ServiceProfileLastMileProductCatalog) SetWebUrl(v string) {
	o.WebUrl = &v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise.
func (o *ServiceProfileLastMileProductCatalog) GetDeliveryDate() ServiceProfileLastMileDeliveryDateRange {
	if o == nil || IsNil(o.DeliveryDate) {
		var ret ServiceProfileLastMileDeliveryDateRange
		return ret
	}
	return *o.DeliveryDate
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProfileLastMileProductCatalog) GetDeliveryDateOk() (*ServiceProfileLastMileDeliveryDateRange, bool) {
	if o == nil || IsNil(o.DeliveryDate) {
		return nil, false
	}
	return o.DeliveryDate, true
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *ServiceProfileLastMileProductCatalog) HasDeliveryDate() bool {
	if o != nil && !IsNil(o.DeliveryDate) {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given ServiceProfileLastMileDeliveryDateRange and assigns it to the DeliveryDate field.
func (o *ServiceProfileLastMileProductCatalog) SetDeliveryDate(v ServiceProfileLastMileDeliveryDateRange) {
	o.DeliveryDate = &v
}

// GetOfferings returns the Offerings field value if set, zero value otherwise.
func (o *ServiceProfileLastMileProductCatalog) GetOfferings() []ServiceProfileLastMileOffering {
	if o == nil || IsNil(o.Offerings) {
		var ret []ServiceProfileLastMileOffering
		return ret
	}
	return o.Offerings
}

// GetOfferingsOk returns a tuple with the Offerings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProfileLastMileProductCatalog) GetOfferingsOk() ([]ServiceProfileLastMileOffering, bool) {
	if o == nil || IsNil(o.Offerings) {
		return nil, false
	}
	return o.Offerings, true
}

// HasOfferings returns a boolean if a field has been set.
func (o *ServiceProfileLastMileProductCatalog) HasOfferings() bool {
	if o != nil && !IsNil(o.Offerings) {
		return true
	}

	return false
}

// SetOfferings gets a reference to the given []ServiceProfileLastMileOffering and assigns it to the Offerings field.
func (o *ServiceProfileLastMileProductCatalog) SetOfferings(v []ServiceProfileLastMileOffering) {
	o.Offerings = v
}

func (o ServiceProfileLastMileProductCatalog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceProfileLastMileProductCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.WebUrl) {
		toSerialize["webUrl"] = o.WebUrl
	}
	if !IsNil(o.DeliveryDate) {
		toSerialize["deliveryDate"] = o.DeliveryDate
	}
	if !IsNil(o.Offerings) {
		toSerialize["offerings"] = o.Offerings
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceProfileLastMileProductCatalog) UnmarshalJSON(data []byte) (err error) {
	varServiceProfileLastMileProductCatalog := _ServiceProfileLastMileProductCatalog{}

	err = json.Unmarshal(data, &varServiceProfileLastMileProductCatalog)

	if err != nil {
		return err
	}

	*o = ServiceProfileLastMileProductCatalog(varServiceProfileLastMileProductCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "webUrl")
		delete(additionalProperties, "deliveryDate")
		delete(additionalProperties, "offerings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceProfileLastMileProductCatalog struct {
	value *ServiceProfileLastMileProductCatalog
	isSet bool
}

func (v NullableServiceProfileLastMileProductCatalog) Get() *ServiceProfileLastMileProductCatalog {
	return v.value
}

func (v *NullableServiceProfileLastMileProductCatalog) Set(val *ServiceProfileLastMileProductCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceProfileLastMileProductCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceProfileLastMileProductCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceProfileLastMileProductCatalog(val *ServiceProfileLastMileProductCatalog) *NullableServiceProfileLastMileProductCatalog {
	return &NullableServiceProfileLastMileProductCatalog{value: val, isSet: true}
}

func (v NullableServiceProfileLastMileProductCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceProfileLastMileProductCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
