/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// checks if the AppDomainPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDomainPostRequest{}

// AppDomainPostRequest Create App Domain
type AppDomainPostRequest struct {
	Type AppDomainType `json:"type"`
	// Customer-provided App Domain name
	Name string `json:"name"`
	// Customer-provided App Domain description
	Description          *string `json:"description,omitempty"`
	Project              Project `json:"project"`
	AdditionalProperties map[string]interface{}
}

type _AppDomainPostRequest AppDomainPostRequest

// NewAppDomainPostRequest instantiates a new AppDomainPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDomainPostRequest(type_ AppDomainType, name string, project Project) *AppDomainPostRequest {
	this := AppDomainPostRequest{}
	this.Type = type_
	this.Name = name
	this.Project = project
	return &this
}

// NewAppDomainPostRequestWithDefaults instantiates a new AppDomainPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDomainPostRequestWithDefaults() *AppDomainPostRequest {
	this := AppDomainPostRequest{}
	var type_ AppDomainType = APPDOMAINTYPE_APP_DOMAIN
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *AppDomainPostRequest) GetType() AppDomainType {
	if o == nil {
		var ret AppDomainType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppDomainPostRequest) GetTypeOk() (*AppDomainType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppDomainPostRequest) SetType(v AppDomainType) {
	o.Type = v
}

// GetName returns the Name field value
func (o *AppDomainPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppDomainPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppDomainPostRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AppDomainPostRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDomainPostRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AppDomainPostRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AppDomainPostRequest) SetDescription(v string) {
	o.Description = &v
}

// GetProject returns the Project field value
func (o *AppDomainPostRequest) GetProject() Project {
	if o == nil {
		var ret Project
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *AppDomainPostRequest) GetProjectOk() (*Project, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *AppDomainPostRequest) SetProject(v Project) {
	o.Project = v
}

func (o AppDomainPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDomainPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["project"] = o.Project

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppDomainPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"project",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppDomainPostRequest := _AppDomainPostRequest{}

	err = json.Unmarshal(data, &varAppDomainPostRequest)

	if err != nil {
		return err
	}

	*o = AppDomainPostRequest(varAppDomainPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "project")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppDomainPostRequest struct {
	value *AppDomainPostRequest
	isSet bool
}

func (v NullableAppDomainPostRequest) Get() *AppDomainPostRequest {
	return v.value
}

func (v *NullableAppDomainPostRequest) Set(val *AppDomainPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDomainPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDomainPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDomainPostRequest(val *AppDomainPostRequest) *NullableAppDomainPostRequest {
	return &NullableAppDomainPostRequest{value: val, isSet: true}
}

func (v NullableAppDomainPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDomainPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
