/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ExchangeServiceSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExchangeServiceSearchRequest{}

// ExchangeServiceSearchRequest Search requests containing criteria
type ExchangeServiceSearchRequest struct {
	Filter               *ExchangeServiceSearchExpression    `json:"filter,omitempty"`
	Pagination           *PaginationRequest                  `json:"pagination,omitempty"`
	Sort                 []ExchangeServiceSearchSortCriteria `json:"sort,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExchangeServiceSearchRequest ExchangeServiceSearchRequest

// NewExchangeServiceSearchRequest instantiates a new ExchangeServiceSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchangeServiceSearchRequest() *ExchangeServiceSearchRequest {
	this := ExchangeServiceSearchRequest{}
	return &this
}

// NewExchangeServiceSearchRequestWithDefaults instantiates a new ExchangeServiceSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchangeServiceSearchRequestWithDefaults() *ExchangeServiceSearchRequest {
	this := ExchangeServiceSearchRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *ExchangeServiceSearchRequest) GetFilter() ExchangeServiceSearchExpression {
	if o == nil || IsNil(o.Filter) {
		var ret ExchangeServiceSearchExpression
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExchangeServiceSearchRequest) GetFilterOk() (*ExchangeServiceSearchExpression, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ExchangeServiceSearchRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given ExchangeServiceSearchExpression and assigns it to the Filter field.
func (o *ExchangeServiceSearchRequest) SetFilter(v ExchangeServiceSearchExpression) {
	o.Filter = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ExchangeServiceSearchRequest) GetPagination() PaginationRequest {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationRequest
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExchangeServiceSearchRequest) GetPaginationOk() (*PaginationRequest, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ExchangeServiceSearchRequest) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationRequest and assigns it to the Pagination field.
func (o *ExchangeServiceSearchRequest) SetPagination(v PaginationRequest) {
	o.Pagination = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *ExchangeServiceSearchRequest) GetSort() []ExchangeServiceSearchSortCriteria {
	if o == nil || IsNil(o.Sort) {
		var ret []ExchangeServiceSearchSortCriteria
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExchangeServiceSearchRequest) GetSortOk() ([]ExchangeServiceSearchSortCriteria, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *ExchangeServiceSearchRequest) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []ExchangeServiceSearchSortCriteria and assigns it to the Sort field.
func (o *ExchangeServiceSearchRequest) SetSort(v []ExchangeServiceSearchSortCriteria) {
	o.Sort = v
}

func (o ExchangeServiceSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExchangeServiceSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExchangeServiceSearchRequest) UnmarshalJSON(data []byte) (err error) {
	varExchangeServiceSearchRequest := _ExchangeServiceSearchRequest{}

	err = json.Unmarshal(data, &varExchangeServiceSearchRequest)

	if err != nil {
		return err
	}

	*o = ExchangeServiceSearchRequest(varExchangeServiceSearchRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filter")
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "sort")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExchangeServiceSearchRequest struct {
	value *ExchangeServiceSearchRequest
	isSet bool
}

func (v NullableExchangeServiceSearchRequest) Get() *ExchangeServiceSearchRequest {
	return v.value
}

func (v *NullableExchangeServiceSearchRequest) Set(val *ExchangeServiceSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExchangeServiceSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExchangeServiceSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchangeServiceSearchRequest(val *ExchangeServiceSearchRequest) *NullableExchangeServiceSearchRequest {
	return &NullableExchangeServiceSearchRequest{value: val, isSet: true}
}

func (v NullableExchangeServiceSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchangeServiceSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
