/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// checks if the AppSubscriptionSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSubscriptionSource{}

// AppSubscriptionSource Source details for the Subscription
type AppSubscriptionSource struct {
	AppLink *AppSubscriptionSourceAppLink `json:"appLink,omitempty"`
	// List of IP subnets in CIDR notation
	IpSubnets            []string `json:"ipSubnets"`
	AdditionalProperties map[string]interface{}
}

type _AppSubscriptionSource AppSubscriptionSource

// NewAppSubscriptionSource instantiates a new AppSubscriptionSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSubscriptionSource(ipSubnets []string) *AppSubscriptionSource {
	this := AppSubscriptionSource{}
	this.IpSubnets = ipSubnets
	return &this
}

// NewAppSubscriptionSourceWithDefaults instantiates a new AppSubscriptionSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSubscriptionSourceWithDefaults() *AppSubscriptionSource {
	this := AppSubscriptionSource{}
	return &this
}

// GetAppLink returns the AppLink field value if set, zero value otherwise.
func (o *AppSubscriptionSource) GetAppLink() AppSubscriptionSourceAppLink {
	if o == nil || IsNil(o.AppLink) {
		var ret AppSubscriptionSourceAppLink
		return ret
	}
	return *o.AppLink
}

// GetAppLinkOk returns a tuple with the AppLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppSubscriptionSource) GetAppLinkOk() (*AppSubscriptionSourceAppLink, bool) {
	if o == nil || IsNil(o.AppLink) {
		return nil, false
	}
	return o.AppLink, true
}

// HasAppLink returns a boolean if a field has been set.
func (o *AppSubscriptionSource) HasAppLink() bool {
	if o != nil && !IsNil(o.AppLink) {
		return true
	}

	return false
}

// SetAppLink gets a reference to the given AppSubscriptionSourceAppLink and assigns it to the AppLink field.
func (o *AppSubscriptionSource) SetAppLink(v AppSubscriptionSourceAppLink) {
	o.AppLink = &v
}

// GetIpSubnets returns the IpSubnets field value
func (o *AppSubscriptionSource) GetIpSubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.IpSubnets
}

// GetIpSubnetsOk returns a tuple with the IpSubnets field value
// and a boolean to check if the value has been set.
func (o *AppSubscriptionSource) GetIpSubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpSubnets, true
}

// SetIpSubnets sets field value
func (o *AppSubscriptionSource) SetIpSubnets(v []string) {
	o.IpSubnets = v
}

func (o AppSubscriptionSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSubscriptionSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppLink) {
		toSerialize["appLink"] = o.AppLink
	}
	toSerialize["ipSubnets"] = o.IpSubnets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppSubscriptionSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ipSubnets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppSubscriptionSource := _AppSubscriptionSource{}

	err = json.Unmarshal(data, &varAppSubscriptionSource)

	if err != nil {
		return err
	}

	*o = AppSubscriptionSource(varAppSubscriptionSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "appLink")
		delete(additionalProperties, "ipSubnets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppSubscriptionSource struct {
	value *AppSubscriptionSource
	isSet bool
}

func (v NullableAppSubscriptionSource) Get() *AppSubscriptionSource {
	return v.value
}

func (v *NullableAppSubscriptionSource) Set(val *AppSubscriptionSource) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSubscriptionSource) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSubscriptionSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSubscriptionSource(val *AppSubscriptionSource) *NullableAppSubscriptionSource {
	return &NullableAppSubscriptionSource{value: val, isSet: true}
}

func (v NullableAppSubscriptionSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSubscriptionSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
