/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// LoaPatchPanelConnectorType Connector Type
type LoaPatchPanelConnectorType string

// List of LoaPatchPanelConnectorType
const (
	LOAPATCHPANELCONNECTORTYPE_FC LoaPatchPanelConnectorType = "FC"
	LOAPATCHPANELCONNECTORTYPE_SC LoaPatchPanelConnectorType = "SC"
	LOAPATCHPANELCONNECTORTYPE_LC LoaPatchPanelConnectorType = "LC"
	LOAPATCHPANELCONNECTORTYPE_ST LoaPatchPanelConnectorType = "ST"
)

// All allowed values of LoaPatchPanelConnectorType enum
var AllowedLoaPatchPanelConnectorTypeEnumValues = []LoaPatchPanelConnectorType{
	"FC",
	"SC",
	"LC",
	"ST",
}

func (v *LoaPatchPanelConnectorType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LoaPatchPanelConnectorType(value)
	for _, existing := range AllowedLoaPatchPanelConnectorTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LoaPatchPanelConnectorType", value)
}

// NewLoaPatchPanelConnectorTypeFromValue returns a pointer to a valid LoaPatchPanelConnectorType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLoaPatchPanelConnectorTypeFromValue(v string) (*LoaPatchPanelConnectorType, error) {
	ev := LoaPatchPanelConnectorType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LoaPatchPanelConnectorType: valid values are %v", v, AllowedLoaPatchPanelConnectorTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LoaPatchPanelConnectorType) IsValid() bool {
	for _, existing := range AllowedLoaPatchPanelConnectorTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LoaPatchPanelConnectorType value
func (v LoaPatchPanelConnectorType) Ptr() *LoaPatchPanelConnectorType {
	return &v
}

type NullableLoaPatchPanelConnectorType struct {
	value *LoaPatchPanelConnectorType
	isSet bool
}

func (v NullableLoaPatchPanelConnectorType) Get() *LoaPatchPanelConnectorType {
	return v.value
}

func (v *NullableLoaPatchPanelConnectorType) Set(val *LoaPatchPanelConnectorType) {
	v.value = val
	v.isSet = true
}

func (v NullableLoaPatchPanelConnectorType) IsSet() bool {
	return v.isSet
}

func (v *NullableLoaPatchPanelConnectorType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoaPatchPanelConnectorType(val *LoaPatchPanelConnectorType) *NullableLoaPatchPanelConnectorType {
	return &NullableLoaPatchPanelConnectorType{value: val, isSet: true}
}

func (v NullableLoaPatchPanelConnectorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoaPatchPanelConnectorType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
