/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ContactPreference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactPreference{}

// ContactPreference Contact preference for the phone number
type ContactPreference struct {
	// Timezone of the contact preference
	Timezone             *string                        `json:"timezone,omitempty"`
	Availability         *ContactPreferenceAvailability `json:"availability,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ContactPreference ContactPreference

// NewContactPreference instantiates a new ContactPreference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactPreference() *ContactPreference {
	this := ContactPreference{}
	return &this
}

// NewContactPreferenceWithDefaults instantiates a new ContactPreference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactPreferenceWithDefaults() *ContactPreference {
	this := ContactPreference{}
	return &this
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *ContactPreference) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactPreference) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *ContactPreference) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *ContactPreference) SetTimezone(v string) {
	o.Timezone = &v
}

// GetAvailability returns the Availability field value if set, zero value otherwise.
func (o *ContactPreference) GetAvailability() ContactPreferenceAvailability {
	if o == nil || IsNil(o.Availability) {
		var ret ContactPreferenceAvailability
		return ret
	}
	return *o.Availability
}

// GetAvailabilityOk returns a tuple with the Availability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactPreference) GetAvailabilityOk() (*ContactPreferenceAvailability, bool) {
	if o == nil || IsNil(o.Availability) {
		return nil, false
	}
	return o.Availability, true
}

// HasAvailability returns a boolean if a field has been set.
func (o *ContactPreference) HasAvailability() bool {
	if o != nil && !IsNil(o.Availability) {
		return true
	}

	return false
}

// SetAvailability gets a reference to the given ContactPreferenceAvailability and assigns it to the Availability field.
func (o *ContactPreference) SetAvailability(v ContactPreferenceAvailability) {
	o.Availability = &v
}

func (o ContactPreference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactPreference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Availability) {
		toSerialize["availability"] = o.Availability
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContactPreference) UnmarshalJSON(data []byte) (err error) {
	varContactPreference := _ContactPreference{}

	err = json.Unmarshal(data, &varContactPreference)

	if err != nil {
		return err
	}

	*o = ContactPreference(varContactPreference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "availability")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContactPreference struct {
	value *ContactPreference
	isSet bool
}

func (v NullableContactPreference) Get() *ContactPreference {
	return v.value
}

func (v *NullableContactPreference) Set(val *ContactPreference) {
	v.value = val
	v.isSet = true
}

func (v NullableContactPreference) IsSet() bool {
	return v.isSet
}

func (v *NullableContactPreference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactPreference(val *ContactPreference) *NullableContactPreference {
	return &NullableContactPreference{value: val, isSet: true}
}

func (v NullableContactPreference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactPreference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
