/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the StreamFilterSimpleExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamFilterSimpleExpression{}

// StreamFilterSimpleExpression struct for StreamFilterSimpleExpression
type StreamFilterSimpleExpression struct {
	// Possible field names to use on filters:  * `/subject` - subject  * `/type` - type
	Property *string `json:"property,omitempty"`
	// Possible operators to use on filters:  * `=` - equal  * `in` - in  * `LIKE` - case-sensitive like  * `ILIKE` - case-insensitive like
	Operator             *string  `json:"operator,omitempty"`
	Values               []string `json:"values,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StreamFilterSimpleExpression StreamFilterSimpleExpression

// NewStreamFilterSimpleExpression instantiates a new StreamFilterSimpleExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamFilterSimpleExpression() *StreamFilterSimpleExpression {
	this := StreamFilterSimpleExpression{}
	return &this
}

// NewStreamFilterSimpleExpressionWithDefaults instantiates a new StreamFilterSimpleExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamFilterSimpleExpressionWithDefaults() *StreamFilterSimpleExpression {
	this := StreamFilterSimpleExpression{}
	return &this
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *StreamFilterSimpleExpression) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamFilterSimpleExpression) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *StreamFilterSimpleExpression) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *StreamFilterSimpleExpression) SetProperty(v string) {
	o.Property = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *StreamFilterSimpleExpression) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamFilterSimpleExpression) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *StreamFilterSimpleExpression) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *StreamFilterSimpleExpression) SetOperator(v string) {
	o.Operator = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *StreamFilterSimpleExpression) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamFilterSimpleExpression) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *StreamFilterSimpleExpression) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *StreamFilterSimpleExpression) SetValues(v []string) {
	o.Values = v
}

func (o StreamFilterSimpleExpression) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamFilterSimpleExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StreamFilterSimpleExpression) UnmarshalJSON(data []byte) (err error) {
	varStreamFilterSimpleExpression := _StreamFilterSimpleExpression{}

	err = json.Unmarshal(data, &varStreamFilterSimpleExpression)

	if err != nil {
		return err
	}

	*o = StreamFilterSimpleExpression(varStreamFilterSimpleExpression)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "property")
		delete(additionalProperties, "operator")
		delete(additionalProperties, "values")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStreamFilterSimpleExpression struct {
	value *StreamFilterSimpleExpression
	isSet bool
}

func (v NullableStreamFilterSimpleExpression) Get() *StreamFilterSimpleExpression {
	return v.value
}

func (v *NullableStreamFilterSimpleExpression) Set(val *StreamFilterSimpleExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamFilterSimpleExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamFilterSimpleExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamFilterSimpleExpression(val *StreamFilterSimpleExpression) *NullableStreamFilterSimpleExpression {
	return &NullableStreamFilterSimpleExpression{value: val, isSet: true}
}

func (v NullableStreamFilterSimpleExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamFilterSimpleExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
