/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// checks if the LoaActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoaActionRequest{}

// LoaActionRequest Action Request
type LoaActionRequest struct {
	Type                 LoaActionType  `json:"type"`
	Data                 *LoaActionData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LoaActionRequest LoaActionRequest

// NewLoaActionRequest instantiates a new LoaActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoaActionRequest(type_ LoaActionType) *LoaActionRequest {
	this := LoaActionRequest{}
	this.Type = type_
	return &this
}

// NewLoaActionRequestWithDefaults instantiates a new LoaActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoaActionRequestWithDefaults() *LoaActionRequest {
	this := LoaActionRequest{}
	return &this
}

// GetType returns the Type field value
func (o *LoaActionRequest) GetType() LoaActionType {
	if o == nil {
		var ret LoaActionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *LoaActionRequest) GetTypeOk() (*LoaActionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *LoaActionRequest) SetType(v LoaActionType) {
	o.Type = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LoaActionRequest) GetData() LoaActionData {
	if o == nil || IsNil(o.Data) {
		var ret LoaActionData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoaActionRequest) GetDataOk() (*LoaActionData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LoaActionRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given LoaActionData and assigns it to the Data field.
func (o *LoaActionRequest) SetData(v LoaActionData) {
	o.Data = &v
}

func (o LoaActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoaActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoaActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoaActionRequest := _LoaActionRequest{}

	err = json.Unmarshal(data, &varLoaActionRequest)

	if err != nil {
		return err
	}

	*o = LoaActionRequest(varLoaActionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoaActionRequest struct {
	value *LoaActionRequest
	isSet bool
}

func (v NullableLoaActionRequest) Get() *LoaActionRequest {
	return v.value
}

func (v *NullableLoaActionRequest) Set(val *LoaActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoaActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoaActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoaActionRequest(val *LoaActionRequest) *NullableLoaActionRequest {
	return &NullableLoaActionRequest{value: val, isSet: true}
}

func (v NullableLoaActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoaActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
