/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the SearchStreamResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchStreamResponse{}

// SearchStreamResponse struct for SearchStreamResponse
type SearchStreamResponse struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	// Data returned from the API call.
	Data                 []Stream `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchStreamResponse SearchStreamResponse

// NewSearchStreamResponse instantiates a new SearchStreamResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchStreamResponse() *SearchStreamResponse {
	this := SearchStreamResponse{}
	return &this
}

// NewSearchStreamResponseWithDefaults instantiates a new SearchStreamResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchStreamResponseWithDefaults() *SearchStreamResponse {
	this := SearchStreamResponse{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *SearchStreamResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchStreamResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *SearchStreamResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *SearchStreamResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SearchStreamResponse) GetData() []Stream {
	if o == nil || IsNil(o.Data) {
		var ret []Stream
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchStreamResponse) GetDataOk() ([]Stream, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SearchStreamResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Stream and assigns it to the Data field.
func (o *SearchStreamResponse) SetData(v []Stream) {
	o.Data = v
}

func (o SearchStreamResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchStreamResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchStreamResponse) UnmarshalJSON(data []byte) (err error) {
	varSearchStreamResponse := _SearchStreamResponse{}

	err = json.Unmarshal(data, &varSearchStreamResponse)

	if err != nil {
		return err
	}

	*o = SearchStreamResponse(varSearchStreamResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchStreamResponse struct {
	value *SearchStreamResponse
	isSet bool
}

func (v NullableSearchStreamResponse) Get() *SearchStreamResponse {
	return v.value
}

func (v *NullableSearchStreamResponse) Set(val *SearchStreamResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchStreamResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchStreamResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchStreamResponse(val *SearchStreamResponse) *NullableSearchStreamResponse {
	return &NullableSearchStreamResponse{value: val, isSet: true}
}

func (v NullableSearchStreamResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchStreamResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
