/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the AppSubscriptionSimpleExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSubscriptionSimpleExpression{}

// AppSubscriptionSimpleExpression struct for AppSubscriptionSimpleExpression
type AppSubscriptionSimpleExpression struct {
	// Possible field names to use on filters:   * `/project/projectId` - project id   * `/uuid` - App Subscription uuid   * `/state` - App Subscription status   * `/source/appLink/uuid` - Source App Link uuid   * `/source/ipSubnets` - Source App Link ip subnets   * `/target/appService/uuid` - Target App Service uuid   * `/target/geoScope` - Target App Service geo scope   * `/target/prioritization` - Target App Service prioritization   * `/changeLog/createdDateTime` - App Subscription creation timestamp   * `/changeLog/updatedDateTime` - App Subscription last updated timestamp   * `/changeLog/deletedDateTime` - App Subscription deletion timestamp
	Property *string `json:"property,omitempty"`
	// Possible operators to use on filters:   * `=` - equal   * `!=` - not equal   * `>` - greater than   * `<` - less than   * `IN` - in   * `NOT IN` - not in   * `LIKE` - like   * `ILIKE` - case-insensitive like   * `BETWEEN` - between   * `NOT BETWEEN` - not between
	Operator             *string  `json:"operator,omitempty"`
	Values               []string `json:"values,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AppSubscriptionSimpleExpression AppSubscriptionSimpleExpression

// NewAppSubscriptionSimpleExpression instantiates a new AppSubscriptionSimpleExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSubscriptionSimpleExpression() *AppSubscriptionSimpleExpression {
	this := AppSubscriptionSimpleExpression{}
	return &this
}

// NewAppSubscriptionSimpleExpressionWithDefaults instantiates a new AppSubscriptionSimpleExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSubscriptionSimpleExpressionWithDefaults() *AppSubscriptionSimpleExpression {
	this := AppSubscriptionSimpleExpression{}
	return &this
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *AppSubscriptionSimpleExpression) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppSubscriptionSimpleExpression) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *AppSubscriptionSimpleExpression) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *AppSubscriptionSimpleExpression) SetProperty(v string) {
	o.Property = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *AppSubscriptionSimpleExpression) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppSubscriptionSimpleExpression) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *AppSubscriptionSimpleExpression) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *AppSubscriptionSimpleExpression) SetOperator(v string) {
	o.Operator = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *AppSubscriptionSimpleExpression) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppSubscriptionSimpleExpression) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *AppSubscriptionSimpleExpression) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *AppSubscriptionSimpleExpression) SetValues(v []string) {
	o.Values = v
}

func (o AppSubscriptionSimpleExpression) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSubscriptionSimpleExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppSubscriptionSimpleExpression) UnmarshalJSON(data []byte) (err error) {
	varAppSubscriptionSimpleExpression := _AppSubscriptionSimpleExpression{}

	err = json.Unmarshal(data, &varAppSubscriptionSimpleExpression)

	if err != nil {
		return err
	}

	*o = AppSubscriptionSimpleExpression(varAppSubscriptionSimpleExpression)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "property")
		delete(additionalProperties, "operator")
		delete(additionalProperties, "values")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppSubscriptionSimpleExpression struct {
	value *AppSubscriptionSimpleExpression
	isSet bool
}

func (v NullableAppSubscriptionSimpleExpression) Get() *AppSubscriptionSimpleExpression {
	return v.value
}

func (v *NullableAppSubscriptionSimpleExpression) Set(val *AppSubscriptionSimpleExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSubscriptionSimpleExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSubscriptionSimpleExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSubscriptionSimpleExpression(val *AppSubscriptionSimpleExpression) *NullableAppSubscriptionSimpleExpression {
	return &NullableAppSubscriptionSimpleExpression{value: val, isSet: true}
}

func (v NullableAppSubscriptionSimpleExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSubscriptionSimpleExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
