/*
Network Edge APIs

Testing LicensingApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package networkedgev1

import (
	"context"
	"testing"

	openapiclient "github.com/equinix/equinix-sdk-go/services/networkedgev1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_networkedgev1_LicensingApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LicensingApiService UpdateLicenseUsingPOST", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var uuid string

		resp, httpRes, err := apiClient.LicensingApi.UpdateLicenseUsingPOST(context.Background(), uuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LicensingApiService UploadLicenseForDeviceUsingPOST", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var uuid string

		resp, httpRes, err := apiClient.LicensingApi.UploadLicenseForDeviceUsingPOST(context.Background(), uuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LicensingApiService UploadLicenseUsingPOST", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LicensingApi.UploadLicenseUsingPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
