/*
Network Edge APIs

Network Edge (NE) is a platform that allows customers to deploy and run virtual network services and appliances such as routers, load balancers, and firewalls on a generic device instead of additional dedicated hardware, CapEx and colo space. The Network Edge REST APIs allow you to interact with the Equinix Platform to programmatically create a virtual device and add services. Details on specific use cases can be found in the documentation available on the developer portal.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package networkedgev1

import (
	"encoding/json"
)

// checks if the DeviceACLDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceACLDetailsResponse{}

// DeviceACLDetailsResponse struct for DeviceACLDetailsResponse
type DeviceACLDetailsResponse struct {
	// The name of the ACL template.
	Name *string `json:"name,omitempty"`
	// The unique Id of the ACL template.
	Uuid *string `json:"uuid,omitempty"`
	// The description of the ACL template.
	Description *string `json:"description,omitempty"`
	// An array of inbound rules
	InboundRules []InboundRules `json:"inboundRules,omitempty"`
	// Created by
	CreatedBy *string `json:"createdBy,omitempty"`
	// Created date
	CreatedDate *string `json:"createdDate,omitempty"`
	// The status of the ACL template on the device. Possible values are PROVISIONED, DEPROVISIONED, DEVICE_NOT_READY, FAILED, NOT_APPLIED, PROVISIONING.
	Status               *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceACLDetailsResponse DeviceACLDetailsResponse

// NewDeviceACLDetailsResponse instantiates a new DeviceACLDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceACLDetailsResponse() *DeviceACLDetailsResponse {
	this := DeviceACLDetailsResponse{}
	return &this
}

// NewDeviceACLDetailsResponseWithDefaults instantiates a new DeviceACLDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceACLDetailsResponseWithDefaults() *DeviceACLDetailsResponse {
	this := DeviceACLDetailsResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeviceACLDetailsResponse) SetName(v string) {
	o.Name = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *DeviceACLDetailsResponse) SetUuid(v string) {
	o.Uuid = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DeviceACLDetailsResponse) SetDescription(v string) {
	o.Description = &v
}

// GetInboundRules returns the InboundRules field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetInboundRules() []InboundRules {
	if o == nil || IsNil(o.InboundRules) {
		var ret []InboundRules
		return ret
	}
	return o.InboundRules
}

// GetInboundRulesOk returns a tuple with the InboundRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetInboundRulesOk() ([]InboundRules, bool) {
	if o == nil || IsNil(o.InboundRules) {
		return nil, false
	}
	return o.InboundRules, true
}

// HasInboundRules returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasInboundRules() bool {
	if o != nil && !IsNil(o.InboundRules) {
		return true
	}

	return false
}

// SetInboundRules gets a reference to the given []InboundRules and assigns it to the InboundRules field.
func (o *DeviceACLDetailsResponse) SetInboundRules(v []InboundRules) {
	o.InboundRules = v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *DeviceACLDetailsResponse) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetCreatedDate() string {
	if o == nil || IsNil(o.CreatedDate) {
		var ret string
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetCreatedDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given string and assigns it to the CreatedDate field.
func (o *DeviceACLDetailsResponse) SetCreatedDate(v string) {
	o.CreatedDate = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceACLDetailsResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceACLDetailsResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceACLDetailsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeviceACLDetailsResponse) SetStatus(v string) {
	o.Status = &v
}

func (o DeviceACLDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceACLDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InboundRules) {
		toSerialize["inboundRules"] = o.InboundRules
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceACLDetailsResponse) UnmarshalJSON(data []byte) (err error) {
	varDeviceACLDetailsResponse := _DeviceACLDetailsResponse{}

	err = json.Unmarshal(data, &varDeviceACLDetailsResponse)

	if err != nil {
		return err
	}

	*o = DeviceACLDetailsResponse(varDeviceACLDetailsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "description")
		delete(additionalProperties, "inboundRules")
		delete(additionalProperties, "createdBy")
		delete(additionalProperties, "createdDate")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceACLDetailsResponse struct {
	value *DeviceACLDetailsResponse
	isSet bool
}

func (v NullableDeviceACLDetailsResponse) Get() *DeviceACLDetailsResponse {
	return v.value
}

func (v *NullableDeviceACLDetailsResponse) Set(val *DeviceACLDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceACLDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceACLDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceACLDetailsResponse(val *DeviceACLDetailsResponse) *NullableDeviceACLDetailsResponse {
	return &NullableDeviceACLDetailsResponse{value: val, isSet: true}
}

func (v NullableDeviceACLDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceACLDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
