/*
Network Edge APIs

Network Edge (NE) is a platform that allows customers to deploy and run virtual network services and appliances such as routers, load balancers, and firewalls on a generic device instead of additional dedicated hardware, CapEx and colo space. The Network Edge REST APIs allow you to interact with the Equinix Platform to programmatically create a virtual device and add services. Details on specific use cases can be found in the documentation available on the developer portal.

API version: 1.0
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package networkedgev1

import (
	"encoding/json"
)

// checks if the UserPublicKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPublicKeyRequest{}

// UserPublicKeyRequest An object with public key details.
type UserPublicKeyRequest struct {
	// Username.
	Username *string `json:"username,omitempty"`
	// Key name. This field may be required for some vendors. The keyName must be an existing keyName associated with an existing keyValue. To set up a new keyName and keyValue pair, call Create Public Key.
	KeyName              *string `json:"keyName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserPublicKeyRequest UserPublicKeyRequest

// NewUserPublicKeyRequest instantiates a new UserPublicKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPublicKeyRequest() *UserPublicKeyRequest {
	this := UserPublicKeyRequest{}
	return &this
}

// NewUserPublicKeyRequestWithDefaults instantiates a new UserPublicKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPublicKeyRequestWithDefaults() *UserPublicKeyRequest {
	this := UserPublicKeyRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UserPublicKeyRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPublicKeyRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UserPublicKeyRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UserPublicKeyRequest) SetUsername(v string) {
	o.Username = &v
}

// GetKeyName returns the KeyName field value if set, zero value otherwise.
func (o *UserPublicKeyRequest) GetKeyName() string {
	if o == nil || IsNil(o.KeyName) {
		var ret string
		return ret
	}
	return *o.KeyName
}

// GetKeyNameOk returns a tuple with the KeyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPublicKeyRequest) GetKeyNameOk() (*string, bool) {
	if o == nil || IsNil(o.KeyName) {
		return nil, false
	}
	return o.KeyName, true
}

// HasKeyName returns a boolean if a field has been set.
func (o *UserPublicKeyRequest) HasKeyName() bool {
	if o != nil && !IsNil(o.KeyName) {
		return true
	}

	return false
}

// SetKeyName gets a reference to the given string and assigns it to the KeyName field.
func (o *UserPublicKeyRequest) SetKeyName(v string) {
	o.KeyName = &v
}

func (o UserPublicKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPublicKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.KeyName) {
		toSerialize["keyName"] = o.KeyName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserPublicKeyRequest) UnmarshalJSON(data []byte) (err error) {
	varUserPublicKeyRequest := _UserPublicKeyRequest{}

	err = json.Unmarshal(data, &varUserPublicKeyRequest)

	if err != nil {
		return err
	}

	*o = UserPublicKeyRequest(varUserPublicKeyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "keyName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserPublicKeyRequest struct {
	value *UserPublicKeyRequest
	isSet bool
}

func (v NullableUserPublicKeyRequest) Get() *UserPublicKeyRequest {
	return v.value
}

func (v *NullableUserPublicKeyRequest) Set(val *UserPublicKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPublicKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPublicKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPublicKeyRequest(val *UserPublicKeyRequest) *NullableUserPublicKeyRequest {
	return &NullableUserPublicKeyRequest{value: val, isSet: true}
}

func (v NullableUserPublicKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPublicKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
